# Generated by Django 4.2.6 on 2023-11-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='share_status',
            field=models.CharField(choices=[('shared', 'Udostępniony'), ('not_shared', 'Nie udostępniony')], default='not_shared', max_length=20),
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('created', 'Utworzone'), ('started', 'Wystartowane'), ('ended', 'Zakończone')], default='created', max_length=20),
        ),
    ]
