# Generated by Django 3.2.23 on 2023-11-06 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_competition_age_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ForeignKey(limit_choices_to={'is_participant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_in_competition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='participants_count',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='competition',
            name='rounds_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
