# Generated by Django 3.2.23 on 2023-11-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20231106_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='participant',
            new_name='participant_user',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='organization',
            new_name='organization_user',
        ),
        migrations.RenameField(
            model_name='participantcompetition',
            old_name='participant',
            new_name='participant_user',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='participant',
            new_name='participant_user',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='referee',
            new_name='referee_user',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='participants',
        ),
    ]
