# Generated by Django 3.2.23 on 2023-11-22 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20231115_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='name',
            field=models.CharField(default='test', max_length=128),
        ),
        migrations.AddField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(limit_choices_to={'is_participant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
