# Generated by Django 3.2.23 on 2023-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20231203_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='age_restriction',
            field=models.CharField(choices=[('YOUTH', 'Młodzicy'), ('YOUNGER_JUNIORS', 'Młodsi juniorzy'), ('JUNIORS', 'Juniorzy'), ('SENIORS', 'Seniorzy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='discipline',
            field=models.CharField(choices=[('PISTOL', 'Pistolet'), ('RIFLE', 'Karabin'), ('SHOTGUN', 'Strzelba')], max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='share_status',
            field=models.CharField(choices=[('SHARED', 'Udostępniony'), ('NOT_SHARED', 'Nie udostępniony')], default='not_shared', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Utworzone'), ('STARTED', 'Wystartowane'), ('ENDED', 'Zakończone')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='target',
            field=models.CharField(choices=[('STATIC', 'Statyczne'), ('MOVING', 'Ruchome')], max_length=20),
        ),
    ]
