# Generated by Django 3.2.23 on 2023-12-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20231211_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
    ]
