# Generated by Django 3.2.23 on 2023-12-30 12:11

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_competition_is_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.competition'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.User.user_profile_picture_path),
        ),
    ]
